# Site settings
exclude: [README.md, example1.md, example2.md]
title: Bhanu Prakash Vangala
email: bv3hz@umsystem.edu
github: bhanuprakashvangala
twitter: # leave blank if you don’t use Twitter
scholar_id: # Google Scholar ID if available
description: > 
    Hi! I'm Bhanu, a PhD student interested in NLP and efficient machine learning. Here you will find my research, publications, and projects.

baseurl: "" # keep blank unless you're using sub-paths
url: "https://bhanuprakashvangala.github.io" # the base hostname & protocol for your site

# Optional URLs for institutions or projects you’re associated with
# Replace or remove these if not relevant
university_url: "https://www.missouri.edu" # Example: University of Missouri
lab_url: "https://scottgs.mufaculty.umsystem.edu/" # Replace with your lab’s website if applicable


# Build settings
markdown: kramdown
